// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameCategoryProp = "tz_category_prop"

// CategoryProp mapped from table <tz_category_prop>
type CategoryProp struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryID int64 `gorm:"column:category_id;comment:分类id" json:"category_id"`                  // 分类id
	PropID     int64 `gorm:"column:prop_id;comment:商品属性id即表tz_prod_prop中的prop_id" json:"prop_id"` // 商品属性id即表tz_prod_prop中的prop_id
}

// TableName CategoryProp's table name
func (*CategoryProp) TableName() string {
	return TableNameCategoryProp
}
