// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameCategoryBrand = "tz_category_brand"

// CategoryBrand mapped from table <tz_category_brand>
type CategoryBrand struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryID int64 `gorm:"column:category_id;comment:分类id" json:"category_id"` // 分类id
	BrandID    int64 `gorm:"column:brand_id;comment:品牌id" json:"brand_id"`       // 品牌id
}

// TableName CategoryBrand's table name
func (*CategoryBrand) TableName() string {
	return TableNameCategoryBrand
}
