// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameCategory = "tz_category"

// Category 产品类目
type Category struct {
	CategoryID   int64     `gorm:"column:category_id;primaryKey;autoIncrement:true;comment:类目ID" json:"category_id"` // 类目ID
	ShopID       int64     `gorm:"column:shop_id;not null;comment:店铺ID" json:"shop_id"`                              // 店铺ID
	ParentID     int64     `gorm:"column:parent_id;not null;comment:父节点" json:"parent_id"`                           // 父节点
	CategoryName string    `gorm:"column:category_name;not null;comment:产品类目名称" json:"category_name"`                // 产品类目名称
	Icon         string    `gorm:"column:icon;comment:类目图标" json:"icon"`                                             // 类目图标
	Pic          string    `gorm:"column:pic;comment:类目的显示图片" json:"pic"`                                            // 类目的显示图片
	Seq          int32     `gorm:"column:seq;not null;comment:排序" json:"seq"`                                        // 排序
	Status       int32     `gorm:"column:status;not null;default:1;comment:默认是1，表示正常状态,0为下线状态" json:"status"`        // 默认是1，表示正常状态,0为下线状态
	RecTime      time.Time `gorm:"column:rec_time;not null;comment:记录时间" json:"rec_time"`                            // 记录时间
	Grade        int32     `gorm:"column:grade;not null;comment:分类层级" json:"grade"`                                  // 分类层级
	UpdateTime   time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                               // 更新时间
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
