// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameDelivery = "tz_delivery"

// Delivery 物流公司
type Delivery struct {
	DvyID          int64     `gorm:"column:dvy_id;primaryKey;autoIncrement:true;comment:ID" json:"dvy_id"` // ID
	DvyName        string    `gorm:"column:dvy_name;not null;comment:物流公司名称" json:"dvy_name"`              // 物流公司名称
	CompanyHomeURL string    `gorm:"column:company_home_url;comment:公司主页" json:"company_home_url"`         // 公司主页
	RecTime        time.Time `gorm:"column:rec_time;not null;comment:建立时间" json:"rec_time"`                // 建立时间
	ModifyTime     time.Time `gorm:"column:modify_time;not null;comment:修改时间" json:"modify_time"`          // 修改时间
	QueryURL       string    `gorm:"column:query_url;not null;comment:物流查询接口" json:"query_url"`            // 物流查询接口
}

// TableName Delivery's table name
func (*Delivery) TableName() string {
	return TableNameDelivery
}
