// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameIndexImg = "tz_index_img"

// IndexImg 主页轮播图
type IndexImg struct {
	ImgID      int64     `gorm:"column:img_id;primaryKey;autoIncrement:true;comment:主键" json:"img_id"` // 主键
	ShopID     int64     `gorm:"column:shop_id;comment:店铺ID" json:"shop_id"`                           // 店铺ID
	ImgURL     string    `gorm:"column:img_url;not null;comment:图片" json:"img_url"`                    // 图片
	Des        string    `gorm:"column:des;comment:说明文字,描述" json:"des"`                                // 说明文字,描述
	Title      string    `gorm:"column:title;comment:标题" json:"title"`                                 // 标题
	Link       string    `gorm:"column:link;comment:链接" json:"link"`                                   // 链接
	Status     bool      `gorm:"column:status;comment:状态" json:"status"`                               // 状态
	Seq        int32     `gorm:"column:seq;comment:顺序" json:"seq"`                                     // 顺序
	UploadTime time.Time `gorm:"column:upload_time;comment:上传时间" json:"upload_time"`                   // 上传时间
	Relation   int64     `gorm:"column:relation;comment:关联" json:"relation"`                           // 关联
	Type       int32     `gorm:"column:type;comment:类型" json:"type"`                                   // 类型
}

// TableName IndexImg's table name
func (*IndexImg) TableName() string {
	return TableNameIndexImg
}
