// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNotice = "tz_notice"

// Notice mapped from table <tz_notice>
type Notice struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:公告id" json:"id"`               // 公告id
	ShopID      int64     `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                                   // 店铺id
	Title       string    `gorm:"column:title;comment:公告标题" json:"title"`                                       // 公告标题
	Content     string    `gorm:"column:content;comment:公告内容" json:"content"`                                   // 公告内容
	Status      bool      `gorm:"column:status;comment:状态(1:公布 0:撤回)" json:"status"`                            // 状态(1:公布 0:撤回)
	IsTop       int32     `gorm:"column:is_top;comment:是否置顶" json:"is_top"`                                     // 是否置顶
	PublishTime time.Time `gorm:"column:publish_time;comment:发布时间" json:"publish_time"`                         // 发布时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
