// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameProdProp = "tz_prod_prop"

// ProdProp mapped from table <tz_prod_prop>
type ProdProp struct {
	PropID   int64  `gorm:"column:prop_id;primaryKey;autoIncrement:true;comment:属性id" json:"prop_id"` // 属性id
	PropName string `gorm:"column:prop_name;comment:属性名称" json:"prop_name"`                           // 属性名称
	Rule     int32  `gorm:"column:rule;comment:ProdPropRule 1:销售属性(规格); 2:参数属性;" json:"rule"`         // ProdPropRule 1:销售属性(规格); 2:参数属性;
	ShopID   int64  `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                               // 店铺id
}

// TableName ProdProp's table name
func (*ProdProp) TableName() string {
	return TableNameProdProp
}
