// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameProdComm = "tz_prod_comm"

// ProdComm 商品评论
type ProdComm struct {
	ProdCommID   int64     `gorm:"column:prod_comm_id;primaryKey;autoIncrement:true;comment:ID" json:"prod_comm_id"`      // ID
	ProdID       int64     `gorm:"column:prod_id;not null;comment:商品ID" json:"prod_id"`                                   // 商品ID
	OrderItemID  int64     `gorm:"column:order_item_id;comment:订单项ID" json:"order_item_id"`                               // 订单项ID
	UserID       string    `gorm:"column:user_id;comment:评论用户ID" json:"user_id"`                                          // 评论用户ID
	Content      string    `gorm:"column:content;comment:评论内容" json:"content"`                                            // 评论内容
	ReplyContent string    `gorm:"column:reply_content;comment:掌柜回复" json:"reply_content"`                                // 掌柜回复
	RecTime      time.Time `gorm:"column:rec_time;comment:记录时间" json:"rec_time"`                                          // 记录时间
	ReplyTime    time.Time `gorm:"column:reply_time;comment:回复时间" json:"reply_time"`                                      // 回复时间
	ReplySts     int32     `gorm:"column:reply_sts;comment:是否回复 0:未回复  1:已回复" json:"reply_sts"`                           // 是否回复 0:未回复  1:已回复
	Postip       string    `gorm:"column:postip;comment:IP来源" json:"postip"`                                              // IP来源
	Score        int32     `gorm:"column:score;comment:得分，0-5分" json:"score"`                                             // 得分，0-5分
	UsefulCounts int32     `gorm:"column:useful_counts;comment:有用的计数" json:"useful_counts"`                               // 有用的计数
	Pics         string    `gorm:"column:pics;comment:晒图的json字符串" json:"pics"`                                            // 晒图的json字符串
	IsAnonymous  int32     `gorm:"column:is_anonymous;comment:是否匿名(1:是  0:否)" json:"is_anonymous"`                        // 是否匿名(1:是  0:否)
	Status       int32     `gorm:"column:status;comment:是否显示，1:为显示，0:待审核， -1：不通过审核，不显示。 如果需要审核评论，则是0,，否则1" json:"status"` // 是否显示，1:为显示，0:待审核， -1：不通过审核，不显示。 如果需要审核评论，则是0,，否则1
	Evaluate     int32     `gorm:"column:evaluate;comment:评价(0好评 1中评 2差评)" json:"evaluate"`                               // 评价(0好评 1中评 2差评)
}

// TableName ProdComm's table name
func (*ProdComm) TableName() string {
	return TableNameProdComm
}
