// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNamePickAddr = "tz_pick_addr"

// PickAddr 用户配送地址
type PickAddr struct {
	AddrID     int64  `gorm:"column:addr_id;primaryKey;autoIncrement:true;comment:ID" json:"addr_id"` // ID
	AddrName   string `gorm:"column:addr_name;comment:自提点名称" json:"addr_name"`                        // 自提点名称
	Addr       string `gorm:"column:addr;comment:地址" json:"addr"`                                     // 地址
	Mobile     string `gorm:"column:mobile;comment:手机" json:"mobile"`                                 // 手机
	ProvinceID int64  `gorm:"column:province_id;comment:省份ID" json:"province_id"`                     // 省份ID
	Province   string `gorm:"column:province;comment:省份" json:"province"`                             // 省份
	CityID     int64  `gorm:"column:city_id;comment:城市ID" json:"city_id"`                             // 城市ID
	City       string `gorm:"column:city;comment:城市" json:"city"`                                     // 城市
	AreaID     int64  `gorm:"column:area_id;comment:区/县ID" json:"area_id"`                            // 区/县ID
	Area       string `gorm:"column:area;comment:区/县" json:"area"`                                    // 区/县
	ShopID     int64  `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                             // 店铺id
}

// TableName PickAddr's table name
func (*PickAddr) TableName() string {
	return TableNamePickAddr
}
