// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameProd = "tz_prod"

// Prod 商品
type Prod struct {
	ProdID             int64     `gorm:"column:prod_id;primaryKey;autoIncrement:true;comment:产品ID" json:"prod_id"`   // 产品ID
	ProdName           string    `gorm:"column:prod_name;not null;comment:商品名称" json:"prod_name"`                    // 商品名称
	ShopID             int64     `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                                 // 店铺id
	OriPrice           float64   `gorm:"column:ori_price;default:0.00;comment:原价" json:"ori_price"`                  // 原价
	Price              float64   `gorm:"column:price;comment:现价" json:"price"`                                       // 现价
	Brief              string    `gorm:"column:brief;comment:简要描述,卖点等" json:"brief"`                                 // 简要描述,卖点等
	Content            string    `gorm:"column:content;comment:详细描述" json:"content"`                                 // 详细描述
	Pic                string    `gorm:"column:pic;comment:商品主图" json:"pic"`                                         // 商品主图
	Imgs               string    `gorm:"column:imgs;comment:商品图片，以,分割" json:"imgs"`                                  // 商品图片，以,分割
	Status             int32     `gorm:"column:status;comment:默认是1，表示正常状态, -1表示删除, 0下架" json:"status"`               // 默认是1，表示正常状态, -1表示删除, 0下架
	CategoryID         int64     `gorm:"column:category_id;comment:商品分类" json:"category_id"`                         // 商品分类
	SoldNum            int32     `gorm:"column:sold_num;comment:销量" json:"sold_num"`                                 // 销量
	TotalStocks        int32     `gorm:"column:total_stocks;comment:总库存" json:"total_stocks"`                        // 总库存
	DeliveryMode       string    `gorm:"column:delivery_mode;comment:配送方式json见TransportModeVO" json:"delivery_mode"` // 配送方式json见TransportModeVO
	DeliveryTemplateID int64     `gorm:"column:delivery_template_id;comment:运费模板id" json:"delivery_template_id"`     // 运费模板id
	CreateTime         time.Time `gorm:"column:create_time;comment:录入时间" json:"create_time"`                         // 录入时间
	UpdateTime         time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`                         // 修改时间
	PutawayTime        time.Time `gorm:"column:putaway_time;comment:上架时间" json:"putaway_time"`                       // 上架时间
	Version            int32     `gorm:"column:version;comment:版本 乐观锁" json:"version"`                               // 版本 乐观锁
}

// TableName Prod's table name
func (*Prod) TableName() string {
	return TableNameProd
}
