// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameProdTag = "tz_prod_tag"

// ProdTag 商品分组表
type ProdTag struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:分组标签id" json:"id"` // 分组标签id
	Title      string    `gorm:"column:title;comment:分组标题" json:"title"`                           // 分组标题
	ShopID     int64     `gorm:"column:shop_id;comment:店铺Id" json:"shop_id"`                       // 店铺Id
	Status     bool      `gorm:"column:status;comment:状态(1为正常,0为删除)" json:"status"`                // 状态(1为正常,0为删除)
	IsDefault  bool      `gorm:"column:is_default;comment:默认类型(0:商家自定义,1:系统默认)" json:"is_default"` // 默认类型(0:商家自定义,1:系统默认)
	ProdCount  int64     `gorm:"column:prod_count;comment:商品数量" json:"prod_count"`                 // 商品数量
	Style      int32     `gorm:"column:style;comment:列表样式(0:一列一个,1:一列两个,2:一列三个)" json:"style"`     // 列表样式(0:一列一个,1:一列两个,2:一列三个)
	Seq        int32     `gorm:"column:seq;comment:排序" json:"seq"`                                 // 排序
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`               // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`               // 修改时间
	DeleteTime time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`               // 删除时间
}

// TableName ProdTag's table name
func (*ProdTag) TableName() string {
	return TableNameProdTag
}
