// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameProdPropValue = "tz_prod_prop_value"

// ProdPropValue mapped from table <tz_prod_prop_value>
type ProdPropValue struct {
	ValueID   int64  `gorm:"column:value_id;primaryKey;autoIncrement:true;comment:属性值ID" json:"value_id"` // 属性值ID
	PropValue string `gorm:"column:prop_value;comment:属性值名称" json:"prop_value"`                           // 属性值名称
	PropID    int64  `gorm:"column:prop_id;comment:属性ID" json:"prop_id"`                                  // 属性ID
}

// TableName ProdPropValue's table name
func (*ProdPropValue) TableName() string {
	return TableNameProdPropValue
}
