// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameProdFavorite = "tz_prod_favorite"

// ProdFavorite 商品收藏表
type ProdFavorite struct {
	FavoriteID int64     `gorm:"column:favorite_id;primaryKey;autoIncrement:true;comment:主键" json:"favorite_id"` // 主键
	ProdID     int64     `gorm:"column:prod_id;not null;comment:商品ID" json:"prod_id"`                            // 商品ID
	RecTime    time.Time `gorm:"column:rec_time;not null;comment:收藏时间" json:"rec_time"`                          // 收藏时间
	UserID     string    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                            // 用户ID
}

// TableName ProdFavorite's table name
func (*ProdFavorite) TableName() string {
	return TableNameProdFavorite
}
