// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSysMenu = "tz_sys_menu"

// SysMenu 菜单管理
type SysMenu struct {
	MenuID   int64  `gorm:"column:menu_id;primaryKey;autoIncrement:true" json:"menu_id"`
	ParentID int64  `gorm:"column:parent_id;comment:父菜单ID，一级菜单为0" json:"parent_id"`                // 父菜单ID，一级菜单为0
	Name     string `gorm:"column:name;comment:菜单名称" json:"name"`                                  // 菜单名称
	URL      string `gorm:"column:url;comment:菜单URL" json:"url"`                                   // 菜单URL
	Perms    string `gorm:"column:perms;comment:授权(多个用逗号分隔，如：user:list,user:create)" json:"perms"` // 授权(多个用逗号分隔，如：user:list,user:create)
	Type     int32  `gorm:"column:type;comment:类型   0：目录   1：菜单   2：按钮" json:"type"`               // 类型   0：目录   1：菜单   2：按钮
	Icon     string `gorm:"column:icon;comment:菜单图标" json:"icon"`                                  // 菜单图标
	OrderNum int32  `gorm:"column:order_num;comment:排序" json:"order_num"`                          // 排序
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
