// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSysUserRole = "tz_sys_user_role"

// SysUserRole 用户与角色对应关系
type SysUserRole struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID int64 `gorm:"column:user_id;comment:用户ID" json:"user_id"` // 用户ID
	RoleID int64 `gorm:"column:role_id;comment:角色ID" json:"role_id"` // 角色ID
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
