// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSysLog = "tz_sys_log"

// SysLog 系统日志
type SysLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string    `gorm:"column:username;comment:用户名" json:"username"`        // 用户名
	Operation  string    `gorm:"column:operation;comment:用户操作" json:"operation"`     // 用户操作
	Method     string    `gorm:"column:method;comment:请求方法" json:"method"`           // 请求方法
	Params     string    `gorm:"column:params;comment:请求参数" json:"params"`           // 请求参数
	Time       int64     `gorm:"column:time;not null;comment:执行时长(毫秒)" json:"time"`  // 执行时长(毫秒)
	IP         string    `gorm:"column:ip;comment:IP地址" json:"ip"`                   // IP地址
	CreateDate time.Time `gorm:"column:create_date;comment:创建时间" json:"create_date"` // 创建时间
}

// TableName SysLog's table name
func (*SysLog) TableName() string {
	return TableNameSysLog
}
