// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSysUser = "tz_sys_user"

// SysUser 系统用户
type SysUser struct {
	UserID       int64     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username     string    `gorm:"column:username;not null;comment:用户名" json:"username"`      // 用户名
	Password     string    `gorm:"column:password;comment:密码" json:"password"`                // 密码
	Email        string    `gorm:"column:email;comment:邮箱" json:"email"`                      // 邮箱
	Mobile       string    `gorm:"column:mobile;comment:手机号" json:"mobile"`                   // 手机号
	Status       int32     `gorm:"column:status;comment:状态  0：禁用   1：正常" json:"status"`       // 状态  0：禁用   1：正常
	CreateUserID int64     `gorm:"column:create_user_id;comment:创建者ID" json:"create_user_id"` // 创建者ID
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`        // 创建时间
	ShopID       int64     `gorm:"column:shop_id;comment:用户所在的商城Id" json:"shop_id"`           // 用户所在的商城Id
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
