// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSku = "tz_sku"

// Sku 单品SKU表
type Sku struct {
	SkuID        int64     `gorm:"column:sku_id;primaryKey;autoIncrement:true;comment:单品ID" json:"sku_id"`  // 单品ID
	ProdID       int64     `gorm:"column:prod_id;not null;comment:商品ID" json:"prod_id"`                     // 商品ID
	Properties   string    `gorm:"column:properties;comment:销售属性组合字符串 格式是p1:v1;p2:v2" json:"properties"`    // 销售属性组合字符串 格式是p1:v1;p2:v2
	OriPrice     float64   `gorm:"column:ori_price;comment:原价" json:"ori_price"`                            // 原价
	Price        float64   `gorm:"column:price;comment:价格" json:"price"`                                    // 价格
	Stocks       int32     `gorm:"column:stocks;not null;comment:商品在付款减库存的状态下，该sku上未付款的订单数量" json:"stocks"` // 商品在付款减库存的状态下，该sku上未付款的订单数量
	ActualStocks int32     `gorm:"column:actual_stocks;comment:实际库存" json:"actual_stocks"`                  // 实际库存
	UpdateTime   time.Time `gorm:"column:update_time;not null;comment:修改时间" json:"update_time"`             // 修改时间
	RecTime      time.Time `gorm:"column:rec_time;not null;comment:记录时间" json:"rec_time"`                   // 记录时间
	PartyCode    string    `gorm:"column:party_code;comment:商家编码" json:"party_code"`                        // 商家编码
	ModelID      string    `gorm:"column:model_id;comment:商品条形码" json:"model_id"`                           // 商品条形码
	Pic          string    `gorm:"column:pic;comment:sku图片" json:"pic"`                                     // sku图片
	SkuName      string    `gorm:"column:sku_name;comment:sku名称" json:"sku_name"`                           // sku名称
	ProdName     string    `gorm:"column:prod_name;comment:商品名称" json:"prod_name"`                          // 商品名称
	Version      int32     `gorm:"column:version;not null;comment:版本号" json:"version"`                      // 版本号
	Weight       float64   `gorm:"column:weight;comment:商品重量" json:"weight"`                                // 商品重量
	Volume       float64   `gorm:"column:volume;comment:商品体积" json:"volume"`                                // 商品体积
	Status       int32     `gorm:"column:status;default:1;comment:0 禁用 1 启用" json:"status"`                 // 0 禁用 1 启用
	IsDelete     int32     `gorm:"column:is_delete;comment:0 正常 1 已被删除" json:"is_delete"`                   // 0 正常 1 已被删除
}

// TableName Sku's table name
func (*Sku) TableName() string {
	return TableNameSku
}
