// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTranscityFree = "tz_transcity_free"

// TranscityFree mapped from table <tz_transcity_free>
type TranscityFree struct {
	TranscityFreeID int64 `gorm:"column:transcity_free_id;primaryKey;autoIncrement:true;comment:指定条件包邮城市项id" json:"transcity_free_id"` // 指定条件包邮城市项id
	TransfeeFreeID  int64 `gorm:"column:transfee_free_id;comment:指定条件包邮项id" json:"transfee_free_id"`                                   // 指定条件包邮项id
	FreeCityID      int64 `gorm:"column:free_city_id;comment:城市id" json:"free_city_id"`                                                // 城市id
}

// TableName TranscityFree's table name
func (*TranscityFree) TableName() string {
	return TableNameTranscityFree
}
