// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTransport = "tz_transport"

// Transport mapped from table <tz_transport>
type Transport struct {
	TransportID      int64     `gorm:"column:transport_id;primaryKey;autoIncrement:true;comment:运费模板id" json:"transport_id"` // 运费模板id
	TransName        string    `gorm:"column:trans_name;comment:运费模板名称" json:"trans_name"`                                   // 运费模板名称
	CreateTime       time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                   // 创建时间
	ShopID           int64     `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                                           // 店铺id
	ChargeType       int32     `gorm:"column:charge_type;comment:收费方式（0 按件数,1 按重量 2 按体积）" json:"charge_type"`                // 收费方式（0 按件数,1 按重量 2 按体积）
	IsFreeFee        int32     `gorm:"column:is_free_fee;comment:是否包邮 0:不包邮 1:包邮" json:"is_free_fee"`                        // 是否包邮 0:不包邮 1:包邮
	HasFreeCondition int32     `gorm:"column:has_free_condition;comment:是否含有包邮条件 0 否 1是" json:"has_free_condition"`          // 是否含有包邮条件 0 否 1是
}

// TableName Transport's table name
func (*Transport) TableName() string {
	return TableNameTransport
}
