// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTransfee = "tz_transfee"

// Transfee mapped from table <tz_transfee>
type Transfee struct {
	TransfeeID      int64   `gorm:"column:transfee_id;primaryKey;autoIncrement:true;comment:运费项id" json:"transfee_id"` // 运费项id
	TransportID     int64   `gorm:"column:transport_id;comment:运费模板id" json:"transport_id"`                            // 运费模板id
	ContinuousPiece float64 `gorm:"column:continuous_piece;comment:续件数量" json:"continuous_piece"`                      // 续件数量
	FirstPiece      float64 `gorm:"column:first_piece;comment:首件数量" json:"first_piece"`                                // 首件数量
	ContinuousFee   float64 `gorm:"column:continuous_fee;comment:续件费用" json:"continuous_fee"`                          // 续件费用
	FirstFee        float64 `gorm:"column:first_fee;comment:首件费用" json:"first_fee"`                                    // 首件费用
}

// TableName Transfee's table name
func (*Transfee) TableName() string {
	return TableNameTransfee
}
