// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTransfeeFree = "tz_transfee_free"

// TransfeeFree mapped from table <tz_transfee_free>
type TransfeeFree struct {
	TransfeeFreeID int64   `gorm:"column:transfee_free_id;primaryKey;autoIncrement:true;comment:指定条件包邮项id" json:"transfee_free_id"` // 指定条件包邮项id
	TransportID    int64   `gorm:"column:transport_id;comment:运费模板id" json:"transport_id"`                                          // 运费模板id
	FreeType       int32   `gorm:"column:free_type;comment:包邮方式 （0 满x件/重量/体积包邮 1满金额包邮 2满x件/重量/体积且满金额包邮）" json:"free_type"`          // 包邮方式 （0 满x件/重量/体积包邮 1满金额包邮 2满x件/重量/体积且满金额包邮）
	Amount         float64 `gorm:"column:amount;comment:需满金额" json:"amount"`                                                        // 需满金额
	Piece          float64 `gorm:"column:piece;comment:包邮x件/重量/体积" json:"piece"`                                                    // 包邮x件/重量/体积
}

// TableName TransfeeFree's table name
func (*TransfeeFree) TableName() string {
	return TableNameTransfeeFree
}
