// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUser = "tz_user"

// User 用户表
type User struct {
	UserID        string    `gorm:"column:user_id;primaryKey;comment:ID" json:"user_id"`                 // ID
	NickName      string    `gorm:"column:nick_name;comment:用户昵称" json:"nick_name"`                      // 用户昵称
	RealName      string    `gorm:"column:real_name;comment:真实姓名" json:"real_name"`                      // 真实姓名
	UserMail      string    `gorm:"column:user_mail;comment:用户邮箱" json:"user_mail"`                      // 用户邮箱
	LoginPassword string    `gorm:"column:login_password;comment:登录密码" json:"login_password"`            // 登录密码
	PayPassword   string    `gorm:"column:pay_password;comment:支付密码" json:"pay_password"`                // 支付密码
	UserMobile    string    `gorm:"column:user_mobile;comment:手机号码" json:"user_mobile"`                  // 手机号码
	ModifyTime    time.Time `gorm:"column:modify_time;not null;comment:修改时间" json:"modify_time"`         // 修改时间
	UserRegtime   time.Time `gorm:"column:user_regtime;not null;comment:注册时间" json:"user_regtime"`       // 注册时间
	UserRegip     string    `gorm:"column:user_regip;comment:注册IP" json:"user_regip"`                    // 注册IP
	UserLasttime  time.Time `gorm:"column:user_lasttime;comment:最后登录时间" json:"user_lasttime"`            // 最后登录时间
	UserLastip    string    `gorm:"column:user_lastip;comment:最后登录IP" json:"user_lastip"`                // 最后登录IP
	UserMemo      string    `gorm:"column:user_memo;comment:备注" json:"user_memo"`                        // 备注
	Sex           string    `gorm:"column:sex;default:M;comment:M(男) or F(女)" json:"sex"`                // M(男) or F(女)
	BirthDate     string    `gorm:"column:birth_date;comment:例如：2009-11-27" json:"birth_date"`           // 例如：2009-11-27
	Pic           string    `gorm:"column:pic;comment:头像图片路径" json:"pic"`                                // 头像图片路径
	Status        int32     `gorm:"column:status;not null;default:1;comment:状态 1 正常 0 无效" json:"status"` // 状态 1 正常 0 无效
	Score         int32     `gorm:"column:score;comment:用户积分" json:"score"`                              // 用户积分
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
