// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserCollection = "tz_user_collection"

// UserCollection mapped from table <tz_user_collection>
type UserCollection struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:收藏表" json:"id"` // 收藏表
	ProdID     int64     `gorm:"column:prod_id;comment:商品id" json:"prod_id"`                    // 商品id
	UserID     string    `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`           // 用户id
	CreateTime time.Time `gorm:"column:create_time;comment:收藏时间" json:"create_time"`            // 收藏时间
}

// TableName UserCollection's table name
func (*UserCollection) TableName() string {
	return TableNameUserCollection
}
