Name: Mall4-gin
Host: 0.0.0.0
Port: 8085
local: "zh"
db:
  engine: mysql
  username: admin
  password: '123456'
  host: 192.168.1.52
  port: 3306
  charset: utf8mb4
  database: mall4-gin
  showSQL: 'true'
  maxIdleConns: 2
  maxOpenConns: 10
  connMaxLifetime: 30
redis:
  host: "127.0.0.1"
  port: 6379
  pass: ""

jwt:
  secret_key: "gin-randomkey-Xy8!YW&oboSl8a&E+LbiUguRogfO@Hci"
  jwt_header_key: "Authorization"
  jwt_prefix: "Bearer "
  jwt_expire_hour: 24

log:
  level: "debug"
  path: "log" #  日志文件位置
  filename: "sj_cms_log"  # 日志文件名
  max_size: 100 # 进行切割之前,日志文件的最大大小(MB为单位)
  max_age: 100  # 保留旧文件的最大天数
  max_backups: 100 # 保留旧文件的最大个数
  compress: false # 是否压缩
  stacktrace_key: "123213" #
  format: "json"  # 序列化格式